/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721A } from "./ERC721A";
export type { ERC721A__IERC721Receiver } from "./ERC721A__IERC721Receiver";
