name: Setup
description: Ponder monorepo action setup
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: ${{ matrix.node-version }}
    - name: Cache pnpm
      uses: actions/cache@v3
      with:
        key: pnpm-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
        path: ~/.pnpm-store
        restore-keys: pnpm-
    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        key: modules-${{ matrix.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}
        path: |
          node_modules
          docs/node_modules
          examples/**/node_modules
          packages/**/node_modules
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        override: true
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Install dependencies
      shell: bash
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: pnpm i
    - name: Build
      shell: bash
      run: pnpm build
