name: Setup

description: Ponder monorepo action setup

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8.6.10

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 20

    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
