name: Setup

description: Ponder monorepo action setup

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v2.4.0

    - name: Set up node
      uses: actions/setup-node@v3.8.1
      with:
        cache: pnpm
        node-version: ${{ matrix.node-version == 'Node 18' && 18 || 20 }}

    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1.0.10

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Build
      shell: bash
      run: pnpm build

    - name: Link workspace binaries
      shell: bash
      run: pnpm install
