"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SeedScript__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var SeedScript__factory_1 = require("./SeedScript__factory");
Object.defineProperty(exports, "SeedScript__factory", { enumerable: true, get: function () { return SeedScript__factory_1.SeedScript__factory; } });
