import type { GraphQLSchema } from "graphql";
import { printSchema } from "graphql";
import { writeFileSync } from "node:fs";
import path from "node:path";

import { CONFIG } from "@/common/config";
import { formatPrettier } from "@/common/utils";

const header = `
""" Autogenerated file. Do not edit manually. """
`;

const generateSchema = (gqlSchema: GraphQLSchema) => {
  const body = printSchema(gqlSchema);

  const final = formatPrettier(header + body, { parser: "graphql" });

  writeFileSync(
    path.join(CONFIG.GENERATED_DIR_PATH, "schema.graphql"),
    final,
    "utf8"
  );
};

export { generateSchema };
