import Emittery from "emittery";
import { GraphQLSchema, printSchema } from "graphql";
import { writeFileSync } from "node:fs";
import path from "node:path";

import { ensureDirExists } from "@/common/utils";
import { Resources } from "@/Ponder";
import { Schema } from "@/schema/types";

import { buildContractTypes } from "./buildContractTypes";
import { buildEntityTypes } from "./buildEntityTypes";
import { buildEventTypes } from "./buildEventTypes";
import { formatPrettier } from "./utils";

export class CodegenService extends Emittery {
  resources: Resources;

  constructor({ resources }: { resources: Resources }) {
    super();
    this.resources = resources;
  }

  generateAppFile({ schema }: { schema?: Schema } = {}) {
    const entities = schema?.entities || [];

    const raw = `
      /* Autogenerated file. Do not edit manually. */
  
      import { PonderApp } from "@ponder/core";
      import type { Block, Log, Transaction, Model } from "@ponder/core";
      import type { AbiParameterToPrimitiveType } from "abitype";
      import type { BlockTag, Hash } from "viem";

      /* ENTITY TYPES */

      ${buildEntityTypes(entities)}
  
      /* CONTRACT TYPES */

      type CallOverrides =
      | {
          /** The block number at which to execute the contract call. */
          blockNumber?: bigint
          blockTag?: never
        }
      | {
          blockNumber?: never
          /** The block tag at which to execute the contract call. */
          blockTag?: BlockTag
        }

      ${buildContractTypes(this.resources.contracts)}

      /* CONTEXT TYPES */

      export type Context = {
        contracts: {
          ${this.resources.contracts
            .map((contract) => `${contract.name}: ${contract.name};`)
            .join("")}
        },
        entities: {
          ${entities
            .map((entity) => `${entity.name}: Model<${entity.name}>;`)
            .join("")}
        },
      }

  
      /* HANDLER TYPES */
    
      ${buildEventTypes(this.resources.contracts)}

      export const ponder = new PonderApp<AppType>();
    `;

    const final = formatPrettier(raw);

    const filePath = path.join(this.resources.options.generatedDir, "index.ts");
    ensureDirExists(filePath);
    writeFileSync(filePath, final, "utf8");
  }

  generateSchemaFile({ graphqlSchema }: { graphqlSchema: GraphQLSchema }) {
    const header = `
      """ Autogenerated file. Do not edit manually. """
    `;

    const body = printSchema(graphqlSchema);
    const final = header + body;

    const filePath = path.join(
      this.resources.options.generatedDir,
      "schema.graphql"
    );
    ensureDirExists(filePath);
    writeFileSync(filePath, final, "utf8");
  }
}
