import { writeFileSync } from "node:fs";
import path from "node:path";

import { ensureDirExists } from "@/common/utils";
import type { Ponder } from "@/Ponder";

import { formatPrettier } from "./utils";

export const generateApp = ({ ponder }: { ponder: Ponder }) => {
  const raw = `
    /* Autogenerated file. Do not edit manually. */

    import { PonderApp } from "@ponder/core";
    import type { AppType } from "./app";

    export const ponder = new PonderApp<AppType>();
  `;

  const final = formatPrettier(raw);

  const filePath = path.join(ponder.options.GENERATED_DIR_PATH, "index.ts");
  ensureDirExists(filePath);
  writeFileSync(filePath, final, "utf8");
};
