import { printSchema } from "graphql";
import { writeFileSync } from "node:fs";
import path from "node:path";

import { ensureDirExists } from "@/common/utils";
import type { Ponder } from "@/Ponder";

const header = `
""" Autogenerated file. Do not edit manually. """
`;

export const generateSchema = ({ ponder }: { ponder: Ponder }) => {
  if (!ponder.graphqlSchema) return;

  const body = printSchema(ponder.graphqlSchema);
  const final = header + body;

  const filePath = path.join(
    ponder.options.GENERATED_DIR_PATH,
    "schema.graphql"
  );
  ensureDirExists(filePath);
  writeFileSync(filePath, final, "utf8");
};
