import { writeFileSync } from "node:fs";
import path from "node:path";

import { logger } from "@/common/logger";
import { ensureDirExists } from "@/common/utils";
import type { Ponder } from "@/Ponder";

import { buildEntityTypes } from "./buildEntityTypes";
import { buildEventTypes } from "./buildEventTypes";
import { formatPrettier } from "./utils";

export const generateHandlerTypes = ({ ponder }: { ponder: Ponder }) => {
  const contractNames = ponder.sources.map((source) => source.name);
  const entityNames = (ponder.schema.entities || []).map(
    (entity) => entity.name
  );

  const raw = `/* Autogenerated file. Do not edit manually. */

import type { Block, EventLog, Transaction } from "@ponder/core";
import type { BigNumber, BytesLike } from "ethers";

${contractNames
  .map((name) => `import type { ${name} } from "./contracts/${name}";`)
  .join("\n")}

/* CONTEXT TYPES */

${buildEntityTypes(ponder.schema)}

export type Context = {
  contracts: {
    ${contractNames.map((name) => `${name}: ${name};`).join("")}
  },
  entities: {
    ${entityNames
      .map((entityName) => `${entityName}: ${entityName}Model;`)
      .join("")}
  },
}

/* HANDLER TYPES */

type Hash = string;

${buildEventTypes(ponder.sources)}
  `;

  const final = formatPrettier(raw);

  const filePath = path.join(ponder.options.GENERATED_DIR_PATH, "handlers.ts");
  ensureDirExists(filePath);
  writeFileSync(filePath, final, "utf8");

  logger.debug(`Generated handlers.ts file`);
};
