import Emittery from "emittery";
import { writeFileSync } from "node:fs";
import path from "node:path";

import type { Contract } from "@/config/contracts";
import type { LogFilter } from "@/config/logFilters";
import type { Common } from "@/Ponder";
import { Schema } from "@/schema/types";
import { ensureDirExists } from "@/utils/exists";

import { buildContractTypes } from "./contract";
import { buildEntityTypes } from "./entity";
import { buildEventTypes } from "./event";
import { formatPrettier } from "./prettier";

export class CodegenService extends Emittery {
  private common: Common;
  private contracts: Contract[];
  private logFilters: LogFilter[];

  constructor({
    common,
    contracts,
    logFilters,
  }: {
    common: Common;
    contracts: Contract[];
    logFilters: LogFilter[];
  }) {
    super();
    this.common = common;
    this.contracts = contracts;
    this.logFilters = logFilters;
  }

  generateAppFile({ schema }: { schema?: Schema } = {}) {
    const raw = `
      /* Autogenerated file. Do not edit manually. */
  
      import { PonderApp } from "@ponder/core";
      import type { Block, Log, Transaction, Model, ReadOnlyContract } from "@ponder/core";
      import type { AbiParameterToPrimitiveType } from "abitype";
      import type { BlockTag, Hash } from "viem";

      /* ENTITY TYPES */

      ${buildEntityTypes(schema ?? {})}
  
      /* CONTRACT TYPES */

      ${buildContractTypes(this.contracts)}

      /* CONTEXT TYPES */

      export type Context = {
        contracts: {
          ${this.contracts
            .map((contract) => `${contract.name}: ${contract.name};`)
            .join("")}
        },
        entities: {
          ${Object.keys(schema ?? {})
            .map((tableName) => `${tableName}: Model<${tableName}>;`)
            .join("")}
        },
      }

  
      /* HANDLER TYPES */
    
      ${buildEventTypes(this.logFilters)}

      export const ponder = new PonderApp<AppType>();
    `;

    const final = formatPrettier(raw);

    const filePath = path.join(this.common.options.generatedDir, "index.ts");
    ensureDirExists(filePath);
    writeFileSync(filePath, final, "utf8");

    this.common.logger.debug({
      service: "codegen",
      msg: `Wrote new file at generated/index.ts`,
    });
  }
}
