import { readFile } from "node:fs/promises";

const importObject = {
  env: { abort: () => null },
  index: {
    ["store.get"]: () => null,
    ["store.set"]: () => null,
  },
  conversion: {
    ["typeConversion.bytesToString"]: () => null,
    ["typeConversion.bytesToHex"]: () => null,
    ["typeConversion.bigIntToString"]: () => null,
    ["typeConversion.bigIntToHex"]: () => null,
    ["typeConversion.stringToH160"]: () => null,
    ["typeConversion.bytesToBase58"]: () => null,
  },
  ethereum: { ["ethereum.call"]: () => null },
  numbers: {
    ["bigInt.plus"]: () => null,
    ["bigInt.minus"]: () => null,
    ["bigInt.times"]: () => null,
    ["bigInt.dividedBy"]: () => null,
    ["bigInt.dividedByDecimal"]: () => null,
    ["bigInt.mod"]: () => null,
    ["bigInt.pow"]: () => null,
    ["bigInt.fromString"]: () => null,
    ["bigInt.bitOr"]: () => null,
    ["bigInt.bitAnd"]: () => null,
    ["bigInt.leftShift"]: () => null,
    ["bigInt.rightShift"]: () => null,

    ["bigDecimal.toString"]: () => null,
    ["bigDecimal.fromString"]: () => null,
    ["bigDecimal.plus"]: () => null,
    ["bigDecimal.minus"]: () => null,
    ["bigDecimal.times"]: () => null,
    ["bigDecimal.dividedBy"]: () => null,
    ["bigDecimal.equals"]: () => null,
  },
};

const run = async () => {
  const wasmBuffer = await readFile("./EthPlaysV0.wasm");

  const wasmModule = await WebAssembly.instantiate(wasmBuffer, importObject);

  console.log({ exports: wasmModule.instance.exports });
  /* PRINTS:
  {
    exports: [Object: null prototype] {
      handleAlignmentVote: [Function: 82],
      handleInputVote: [Function: 86],
      handleButtonInput: [Function: 88],
      handleChat: [Function: 91],
      handleRareCandy: [Function: 92],
      handleNewControlBid: [Function: 93],
      handleControl: [Function: 94],
      handleSetIsActive: [Function: 95],
      handleSetAlignmentDecayRate: [Function: 96],
      handleSetChaosVoteReward: [Function: 97],
      handleSetOrderDuration: [Function: 98],
      handleSetChaosInputRewardCooldown: [Function: 99],
      handleSetChaosInputReward: [Function: 100],
      handleSetOrderInputReward: [Function: 101],
      handleSetChatCost: [Function: 102],
      handleSetRareCandyCost: [Function: 103],
      handleSetControlAuctionDuration: [Function: 104],
      handleSetControlDuration: [Function: 105],
      'TypeId.String': Global [WebAssembly.Global] {},
      'TypeId.ArrayBuffer': Global [WebAssembly.Global] {},
      'TypeId.Int8Array': Global [WebAssembly.Global] {},
      'TypeId.Int16Array': Global [WebAssembly.Global] {},
      'TypeId.Int32Array': Global [WebAssembly.Global] {},
      'TypeId.Int64Array': Global [WebAssembly.Global] {},
      'TypeId.Uint8Array': Global [WebAssembly.Global] {},
      'TypeId.Uint16Array': Global [WebAssembly.Global] {},
      'TypeId.Uint32Array': Global [WebAssembly.Global] {},
      'TypeId.Uint64Array': Global [WebAssembly.Global] {},
      'TypeId.Float32Array': Global [WebAssembly.Global] {},
      'TypeId.Float64Array': Global [WebAssembly.Global] {},
      'TypeId.BigDecimal': Global [WebAssembly.Global] {},
      'TypeId.ArrayBool': Global [WebAssembly.Global] {},
      'TypeId.ArrayUint8Array': Global [WebAssembly.Global] {},
      'TypeId.ArrayEthereumValue': Global [WebAssembly.Global] {},
      'TypeId.ArrayStoreValue': Global [WebAssembly.Global] {},
      'TypeId.ArrayJsonValue': Global [WebAssembly.Global] {},
      'TypeId.ArrayString': Global [WebAssembly.Global] {},
      'TypeId.ArrayEventParam': Global [WebAssembly.Global] {},
      'TypeId.ArrayTypedMapEntryStringJsonValue': Global [WebAssembly.Global] {},
      'TypeId.ArrayTypedMapEntryStringStoreValue': Global [WebAssembly.Global] {},
      'TypeId.SmartContractCall': Global [WebAssembly.Global] {},
      'TypeId.EventParam': Global [WebAssembly.Global] {},
      'TypeId.EthereumTransaction': Global [WebAssembly.Global] {},
      'TypeId.EthereumBlock': Global [WebAssembly.Global] {},
      'TypeId.EthereumCall': Global [WebAssembly.Global] {},
      'TypeId.WrappedTypedMapStringJsonValue': Global [WebAssembly.Global] {},
      'TypeId.WrappedBool': Global [WebAssembly.Global] {},
      'TypeId.WrappedJsonValue': Global [WebAssembly.Global] {},
      'TypeId.EthereumValue': Global [WebAssembly.Global] {},
      'TypeId.StoreValue': Global [WebAssembly.Global] {},
      'TypeId.JsonValue': Global [WebAssembly.Global] {},
      'TypeId.EthereumEvent': Global [WebAssembly.Global] {},
      'TypeId.TypedMapEntryStringStoreValue': Global [WebAssembly.Global] {},
      'TypeId.TypedMapEntryStringJsonValue': Global [WebAssembly.Global] {},
      'TypeId.TypedMapStringStoreValue': Global [WebAssembly.Global] {},
      'TypeId.TypedMapStringJsonValue': Global [WebAssembly.Global] {},
      'TypeId.TypedMapStringTypedMapStringJsonValue': Global [WebAssembly.Global] {},
      'TypeId.ResultTypedMapStringJsonValueBool': Global [WebAssembly.Global] {},
      'TypeId.ResultJsonValueBool': Global [WebAssembly.Global] {},
      'TypeId.ArrayU8': Global [WebAssembly.Global] {},
      'TypeId.ArrayU16': Global [WebAssembly.Global] {},
      'TypeId.ArrayU32': Global [WebAssembly.Global] {},
      'TypeId.ArrayU64': Global [WebAssembly.Global] {},
      'TypeId.ArrayI8': Global [WebAssembly.Global] {},
      'TypeId.ArrayI16': Global [WebAssembly.Global] {},
      'TypeId.ArrayI32': Global [WebAssembly.Global] {},
      'TypeId.ArrayI64': Global [WebAssembly.Global] {},
      'TypeId.ArrayF32': Global [WebAssembly.Global] {},
      'TypeId.ArrayF64': Global [WebAssembly.Global] {},
      'TypeId.ArrayBigDecimal': Global [WebAssembly.Global] {},
      'TypeId.NearArrayDataReceiver': Global [WebAssembly.Global] {},
      'TypeId.NearArrayCryptoHash': Global [WebAssembly.Global] {},
      'TypeId.NearArrayActionValue': Global [WebAssembly.Global] {},
      'TypeId.NearMerklePath': Global [WebAssembly.Global] {},
      'TypeId.NearArrayValidatorStake': Global [WebAssembly.Global] {},
      'TypeId.NearArraySlashedValidator': Global [WebAssembly.Global] {},
      'TypeId.NearArraySignature': Global [WebAssembly.Global] {},
      'TypeId.NearArrayChunkHeader': Global [WebAssembly.Global] {},
      'TypeId.NearAccessKeyPermissionValue': Global [WebAssembly.Global] {},
      'TypeId.NearActionValue': Global [WebAssembly.Global] {},
      'TypeId.NearDirection': Global [WebAssembly.Global] {},
      'TypeId.NearPublicKey': Global [WebAssembly.Global] {},
      'TypeId.NearSignature': Global [WebAssembly.Global] {},
      'TypeId.NearFunctionCallPermission': Global [WebAssembly.Global] {},
      'TypeId.NearFullAccessPermission': Global [WebAssembly.Global] {},
      'TypeId.NearAccessKey': Global [WebAssembly.Global] {},
      'TypeId.NearDataReceiver': Global [WebAssembly.Global] {},
      'TypeId.NearCreateAccountAction': Global [WebAssembly.Global] {},
      'TypeId.NearDeployContractAction': Global [WebAssembly.Global] {},
      'TypeId.NearFunctionCallAction': Global [WebAssembly.Global] {},
      'TypeId.NearTransferAction': Global [WebAssembly.Global] {},
      'TypeId.NearStakeAction': Global [WebAssembly.Global] {},
      'TypeId.NearAddKeyAction': Global [WebAssembly.Global] {},
      'TypeId.NearDeleteKeyAction': Global [WebAssembly.Global] {},
      'TypeId.NearDeleteAccountAction': Global [WebAssembly.Global] {},
      'TypeId.NearActionReceipt': Global [WebAssembly.Global] {},
      'TypeId.NearSuccessStatus': Global [WebAssembly.Global] {},
      'TypeId.NearMerklePathItem': Global [WebAssembly.Global] {},
      'TypeId.NearExecutionOutcome': Global [WebAssembly.Global] {},
      'TypeId.NearSlashedValidator': Global [WebAssembly.Global] {},
      'TypeId.NearBlockHeader': Global [WebAssembly.Global] {},
      'TypeId.NearValidatorStake': Global [WebAssembly.Global] {},
      'TypeId.NearChunkHeader': Global [WebAssembly.Global] {},
      'TypeId.NearBlock': Global [WebAssembly.Global] {},
      'TypeId.NearReceiptWithOutcome': Global [WebAssembly.Global] {},
      'TypeId.TransactionReceipt': Global [WebAssembly.Global] {},
      'TypeId.Log': Global [WebAssembly.Global] {},
      'TypeId.ArrayH256': Global [WebAssembly.Global] {},
      'TypeId.ArrayLog': Global [WebAssembly.Global] {},
      'TypeId.CosmosAny': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayAny': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayBytes': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayCoin': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayCommitSig': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayEvent': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayEventAttribute': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayEvidence': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayModeInfo': Global [WebAssembly.Global] {},
      'TypeId.CosmosArraySignerInfo': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayTxResult': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayValidator': Global [WebAssembly.Global] {},
      'TypeId.CosmosArrayValidatorUpdate': Global [WebAssembly.Global] {},
      'TypeId.CosmosAuthInfo': Global [WebAssembly.Global] {},
      'TypeId.CosmosBlock': Global [WebAssembly.Global] {},
      'TypeId.CosmosBlockID': Global [WebAssembly.Global] {},
      'TypeId.CosmosBlockIDFlagEnum': Global [WebAssembly.Global] {},
      'TypeId.CosmosBlockParams': Global [WebAssembly.Global] {},
      'TypeId.CosmosCoin': Global [WebAssembly.Global] {},
      'TypeId.CosmosCommit': Global [WebAssembly.Global] {},
      'TypeId.CosmosCommitSig': Global [WebAssembly.Global] {},
      'TypeId.CosmosCompactBitArray': Global [WebAssembly.Global] {},
      'TypeId.CosmosConsensus': Global [WebAssembly.Global] {},
      'TypeId.CosmosConsensusParams': Global [WebAssembly.Global] {},
      'TypeId.CosmosDuplicateVoteEvidence': Global [WebAssembly.Global] {},
      'TypeId.CosmosDuration': Global [WebAssembly.Global] {},
      'TypeId.CosmosEvent': Global [WebAssembly.Global] {},
      'TypeId.CosmosEventAttribute': Global [WebAssembly.Global] {},
      'TypeId.CosmosEventData': Global [WebAssembly.Global] {},
      'TypeId.CosmosEventVote': Global [WebAssembly.Global] {},
      'TypeId.CosmosEvidence': Global [WebAssembly.Global] {},
      'TypeId.CosmosEvidenceList': Global [WebAssembly.Global] {},
      'TypeId.CosmosEvidenceParams': Global [WebAssembly.Global] {},
      'TypeId.CosmosFee': Global [WebAssembly.Global] {},
      'TypeId.CosmosHeader': Global [WebAssembly.Global] {},
      'TypeId.CosmosHeaderOnlyBlock': Global [WebAssembly.Global] {},
      'TypeId.CosmosLightBlock': Global [WebAssembly.Global] {},
      'TypeId.CosmosLightClientAttackEvidence': Global [WebAssembly.Global] {},
      'TypeId.CosmosModeInfo': Global [WebAssembly.Global] {},
      'TypeId.CosmosModeInfoMulti': Global [WebAssembly.Global] {},
      'TypeId.CosmosModeInfoSingle': Global [WebAssembly.Global] {},
      'TypeId.CosmosPartSetHeader': Global [WebAssembly.Global] {},
      'TypeId.CosmosPublicKey': Global [WebAssembly.Global] {},
      'TypeId.CosmosResponseBeginBlock': Global [WebAssembly.Global] {},
      'TypeId.CosmosResponseDeliverTx': Global [WebAssembly.Global] {},
      'TypeId.CosmosResponseEndBlock': Global [WebAssembly.Global] {},
      'TypeId.CosmosSignModeEnum': Global [WebAssembly.Global] {},
      'TypeId.CosmosSignedHeader': Global [WebAssembly.Global] {},
      'TypeId.CosmosSignedMsgTypeEnum': Global [WebAssembly.Global] {},
      'TypeId.CosmosSignerInfo': Global [WebAssembly.Global] {},
      'TypeId.CosmosTimestamp': Global [WebAssembly.Global] {},
      'TypeId.CosmosTip': Global [WebAssembly.Global] {},
      'TypeId.CosmosTransactionData': Global [WebAssembly.Global] {},
      'TypeId.CosmosTx': Global [WebAssembly.Global] {},
      'TypeId.CosmosTxBody': Global [WebAssembly.Global] {},
      'TypeId.CosmosTxResult': Global [WebAssembly.Global] {},
      'TypeId.CosmosValidator': Global [WebAssembly.Global] {},
      'TypeId.CosmosValidatorParams': Global [WebAssembly.Global] {},
      'TypeId.CosmosValidatorSet': Global [WebAssembly.Global] {},
      'TypeId.CosmosValidatorSetUpdates': Global [WebAssembly.Global] {},
      'TypeId.CosmosValidatorUpdate': Global [WebAssembly.Global] {},
      'TypeId.CosmosVersionParams': Global [WebAssembly.Global] {},
      'TypeId.ArweaveBlock': Global [WebAssembly.Global] {},
      'TypeId.ArweaveProofOfAccess': Global [WebAssembly.Global] {},
      'TypeId.ArweaveTag': Global [WebAssembly.Global] {},
      'TypeId.ArweaveTagArray': Global [WebAssembly.Global] {},
      'TypeId.ArweaveTransaction': Global [WebAssembly.Global] {},
      'TypeId.ArweaveTransactionArray': Global [WebAssembly.Global] {},
      'TypeId.ArweaveTransactionWithBlockPtr': Global [WebAssembly.Global] {},
      id_of_type: [Function: 106],
      allocate: [Function: 107],
      __new: [Function: 11],
      __pin: [Function: 108],
      __unpin: [Function: 109],
      __collect: [Function: 110],
      __rtti_base: Global [WebAssembly.Global] {},
      memory: Memory [WebAssembly.Memory] {},
      _start: [Function: 111]
    }
  }
  */
};

run();
