"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERC721A__IERC721Receiver__factory = exports.ERC721A__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC721A__factory_1 = require("./ERC721A__factory");
Object.defineProperty(exports, "ERC721A__factory", { enumerable: true, get: function () { return ERC721A__factory_1.ERC721A__factory; } });
var ERC721A__IERC721Receiver__factory_1 = require("./ERC721A__IERC721Receiver__factory");
Object.defineProperty(exports, "ERC721A__IERC721Receiver__factory", { enumerable: true, get: function () { return ERC721A__IERC721Receiver__factory_1.ERC721A__IERC721Receiver__factory; } });
