import type { Ponder } from "@ponder/core";
import type { GraphQLSchema } from "graphql";
import { printSchema } from "graphql";
import { writeFileSync } from "node:fs";
import path from "node:path";

import { ensureDirExists } from "@/utils";

const header = `
""" Autogenerated file. Do not edit manually. """
`;

export const generateSchema = (gqlSchema: GraphQLSchema, ponder: Ponder) => {
  const body = printSchema(gqlSchema);

  const final = header + body;

  const filePath = path.join(
    ponder.options.GENERATED_DIR_PATH,
    "schema.graphql"
  );
  ensureDirExists(filePath);
  writeFileSync(filePath, final, "utf8");
};
