"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegistryReceiverV0__factory = exports.Registry__factory = exports.Poke__factory = exports.Ownable__factory = exports.IERC20Metadata__factory = exports.IERC20__factory = exports.EthPlaysV0__factory = exports.ERC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC20__factory_1 = require("./ERC20__factory");
Object.defineProperty(exports, "ERC20__factory", { enumerable: true, get: function () { return ERC20__factory_1.ERC20__factory; } });
var EthPlaysV0__factory_1 = require("./EthPlaysV0__factory");
Object.defineProperty(exports, "EthPlaysV0__factory", { enumerable: true, get: function () { return EthPlaysV0__factory_1.EthPlaysV0__factory; } });
var IERC20__factory_1 = require("./IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
var IERC20Metadata__factory_1 = require("./IERC20Metadata__factory");
Object.defineProperty(exports, "IERC20Metadata__factory", { enumerable: true, get: function () { return IERC20Metadata__factory_1.IERC20Metadata__factory; } });
var Ownable__factory_1 = require("./Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var Poke__factory_1 = require("./Poke__factory");
Object.defineProperty(exports, "Poke__factory", { enumerable: true, get: function () { return Poke__factory_1.Poke__factory; } });
var Registry__factory_1 = require("./Registry__factory");
Object.defineProperty(exports, "Registry__factory", { enumerable: true, get: function () { return Registry__factory_1.Registry__factory; } });
var RegistryReceiverV0__factory_1 = require("./RegistryReceiverV0__factory");
Object.defineProperty(exports, "RegistryReceiverV0__factory", { enumerable: true, get: function () { return RegistryReceiverV0__factory_1.RegistryReceiverV0__factory; } });
