import type { GraphQLSchema } from "graphql";
import { printSchema } from "graphql";
import { writeFile } from "node:fs/promises";

import { toolConfig } from "../config";
import { formatPrettier } from "../preflight";

const header = `
""" Autogenerated file. Do not edit manually. """
`;

const generateSchema = async (gqlSchema: GraphQLSchema) => {
  const body = printSchema(gqlSchema);

  const final = formatPrettier(header + body, { parser: "graphql" });

  await writeFile(`${toolConfig.generatedDir}/schema.graphql`, final, "utf8");

  console.log(`Regenerated schema.graphql`);
};

export { generateSchema };
