import type { GraphQLSchema } from "graphql";
import { printSchema } from "graphql";
import { writeFile } from "node:fs/promises";

import { toolConfig } from "../config";

const header = `
""" Autogenerated file. Do not edit manually. """
`;

const generateSchema = async (gqlSchema: GraphQLSchema) => {
  const body = printSchema(gqlSchema);

  const final = header + body;

  await writeFile(
    `${toolConfig.pathToGeneratedDir}/schema.graphql`,
    final,
    "utf8"
  );

  console.log(`Regenerated schema.graphql`);
};

export { generateSchema };
