import type { GraphQLSchema } from "graphql";
import { printSchema } from "graphql";
import { writeFile } from "node:fs/promises";
import path from "node:path";

import { CONFIG } from "@/common/config";
import { logger } from "@/common/logger";
import { formatPrettier } from "@/common/utils";

const header = `
""" Autogenerated file. Do not edit manually. """
`;

const generateSchema = async (gqlSchema: GraphQLSchema) => {
  const body = printSchema(gqlSchema);

  const final = formatPrettier(header + body, { parser: "graphql" });

  await writeFile(
    path.join(CONFIG.GENERATED_DIR_PATH, "schema.graphql"),
    final,
    "utf8"
  );

  logger.info(`\x1b[36m${"GENERATED SCHEMA"}\x1b[0m`); // magenta
};

export { generateSchema };
