version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - 5001:5001
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - 5432:5432
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  anvil:
    image: ghcr.io/0xolias/simple-anvil-image:main
    environment:
      ANVIL_FORK_URL: "${ANVIL_FORK_URL}"
      ANVIL_FORK_BLOCK_NUMBER: 17500000
    ports:
      - 8545:8545
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
      - 8030:8030
      - 8040:8040
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: postgres
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: mainnet:http://anvil:8545
      ETHEREUM_REORG_THRESHOLD: 0
      GRAPH_LOG: debug
      ETHEREUM_BLOCK_BATCH_SIZE: 30
